In [ ]:
import pandas as pd

import numpy as np

df=pd.read_csv("/BL-Flickr-Images-Book (1).csv")
print(df.head(10))
df.shape

   Identifier              Edition Statement  \
0         206                            NaN
1         216                            NaN
2         218                            NaN
3         472                            NaN
4         480   A new edition, revised, etc.
5         481  Fourth edition, revised, etc.
6         519                            NaN
7         667                            NaN
8         874                            NaN
9        1143                            NaN

                  Place of Publication Date of Publication  \
0                               London         1879 [1878]
1             London; Virtue & Yorston                1868
2                               London                1869
3                               London                1851
4                               London                1857
5                               London                1875
6                               London                1872
7  pp. 40. G. Bryan & Co: Oxford, 1898                 NaN
8                              London]                1676
9                               London                1679

               Publisher                                              Title  \
0       S. Tinsley & Co.                  Walter Forbes. [A novel.] By A. A
1           Virtue & Co.  All for Greed. [A novel. The dedication signed...
2  Bradbury, Evans & Co.  Love the Avenger. By the author of “All for Gr...
3          James Darling  Welsh Sketches, chiefly ecclesiastical, to the...
4   Wertheim & Macintosh  [The World in which I live, and my place in it...
5      William Macintosh  [The World in which I live, and my place in it...
6             The Author  Lagonells. By the author of Darmayne (F. E. A....
7                    NaN  The Coming of Spring, and other poems. By J. A...
8                    NaN  A Warning to the inhabitants of England, and L...
9                    NaN  A Satyr against Vertue. (A poem: supposed to b...

          Author                                  Contributors  \
0          A. A.                               FORBES, Walter.
1      A., A. A.  BLAZE DE BURY, Marie Pauline Rose - Baroness
2      A., A. A.  BLAZE DE BURY, Marie Pauline Rose - Baroness
3      A., E. S.                   Appleyard, Ernest Silvanus.
4      A., E. S.                           BROOME, John Henry.
5      A., E. S.                           BROOME, John Henry.
6      A., F. E.                       ASHLEY, Florence Emily.
7  A., J.|A., J.                 ANDREWS, J. - Writer of Verse
8         Remaʿ.                                  ADAMS, Mary.
9         A., T.                                 OLDHAM, John.

   Corporate Author  Corporate Contributors Former owner  Engraver  \
0               NaN                     NaN          NaN       NaN
1               NaN                     NaN          NaN       NaN
2               NaN                     NaN          NaN       NaN
3               NaN                     NaN          NaN       NaN
4               NaN                     NaN          NaN       NaN
5               NaN                     NaN          NaN       NaN
6               NaN                     NaN          NaN       NaN
7               NaN                     NaN          NaN       NaN
8               NaN                     NaN          NaN       NaN
9               NaN                     NaN          NaN       NaN

  Issuance type                                         Flickr URL  \
0   monographic  http://www.flickr.com/photos/britishlibrary/ta...
1   monographic  http://www.flickr.com/photos/britishlibrary/ta...
2   monographic  http://www.flickr.com/photos/britishlibrary/ta...
3   monographic  http://www.flickr.com/photos/britishlibrary/ta...
4   monographic  http://www.flickr.com/photos/britishlibrary/ta...
5   monographic  http://www.flickr.com/photos/britishlibrary/ta...
6   monographic  http://www.flickr.com/photos/britishlibrary/ta...
7   monographic  http://www.flickr.com/photos/britishlibrary/ta...
8   monographic  http://www.flickr.com/photos/britishlibrary/ta...
9   monographic  http://www.flickr.com/photos/britishlibrary/ta...

                               Shelfmarks
0       British Library HMNTS 12641.b.30.
1       British Library HMNTS 12626.cc.2.
2       British Library HMNTS 12625.dd.1.
3     British Library HMNTS 10369.bbb.15.
4        British Library HMNTS 9007.d.28.
5       British Library HMNTS 9006.ee.10.
6        British Library HMNTS 12637.e.3.
7      British Library HMNTS 011652.g.73.
8      British Library HMNTS 11645.bb.42.
9  British Library HMNTS 11602.ee.10.(2.)

(8287, 15)

In [ ]:
to_drop=["Edition Statement","Former owner","Corporate Author","Corporate Contributors","Contributors","Issuance type","Shelfmarks"]
df.drop(to_drop,inplace=True,axis=1)
df.head()

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Engraver,Flickr URL
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,NaN,http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",NaN,http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",NaN,http://www.flickr.com/photos/britishlibrary/ta...
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",NaN,http://www.flickr.com/photos/britishlibrary/ta...
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",NaN,http://www.flickr.com/photos/britishlibrary/ta...

In [ ]:
for col in df.columns:
  print(col)

Place of Publication
Date of Publication
Publisher
Title
Author
Engraver
Flickr URL

In [ ]:
df.set_index("Identifier",inplace=True)
df.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Engraver,Flickr URL
Identifier,,,,,,,
206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,NaN,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",NaN,http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",NaN,http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",NaN,http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",NaN,http://www.flickr.com/photos/britishlibrary/ta...

In [ ]:
df["Date of Publication"].head(25)

Identifier
206            1879 [1878]
216                   1868
218                   1869
472                   1851
480                   1857
481                   1875
519                   1872
667                    NaN
874                   1676
1143                  1679
1280                  1802
1808                  1859
1905                  1888
1929           1839, 38-54
2836                  1897
2854                  1865
2956               1860-63
2957                  1873
3017                  1866
3131                  1899
4598                  1814
4884                  1820
4976                  1800
5382    1847, 48 [1846-48]
5385               [1897?]
Name: Date of Publication, dtype: object

In [ ]:
print("Removing of unwanted characters")
unwanted_characters=['[',',','-']
def clean_dates(items):
  dop=str(items.loc["Date of Publication"])
  if dop=="non" or dop[0]=="[":
    return np.NaN
  for character in unwanted_characters:
    if character in dop:
      character_index=dop.find(character)
      dop=dop[:character_index]
  return dop
df["Date of Publication"]=df.apply(clean_dates,axis=1)
df["Date of Publication"].head(25)

Removing of unwanted characters

Identifier
206     1879
216      1868
218      1869
472      1851
480      1857
481      1875
519      1872
667       nan
874      1676
1143     1679
1280     1802
1808     1859
1905     1888
1929     1839
2836     1897
2854     1865
2956     1860
2957     1873
3017     1866
3131     1899
4598     1814
4884     1820
4976     1800
5382     1847
5385      NaN
Name: Date of Publication, dtype: object

In [ ]:
print("cleaning the title of the book")
def clean_title(Title):
  if Title=="NaN":
    return "NaN"
  if Title[0]=="[":
    Title=Title[1:Title.find("}")]
  if "by"in Title:
    Title=Title[:Title.find("by")]
  if "By" in Title:
    Title=Title[:Title.find("By")]
  if "[" in Title:
    Title=Title[:Title.find("[")]
  Title=Title[:-2]
  Title=list(map(str.capitalize,Title.split()))
  return ''.join(Title)
df["Title"]=df["Title"].apply(clean_title)
df.head()

cleaning the title of the book

,Place of Publication,Date of Publication,Publisher,Title,Author,Engraver,Flickr URL
Identifier,,,,,,,
206,London,1879,S. Tinsley & Co.,WalterForbes,A. A.,NaN,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,AllForGreed,"A., A. A.",NaN,http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",LoveTheAvenger,"A., A. A.",NaN,http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"WelshSketches,ChieflyEcclesiastical,ToTheClose...","A., E. S.",NaN,http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"TheWorldInWhichILive,AndMyPlaceInIt","A., E. S.",NaN,http://www.flickr.com/photos/britishlibrary/ta...